### ISSUE TITLE
What are solution for this error 

### ISSUE THREAD

**Issue by Saikatsaha1996** [SebaUbuntu/Android-kernel-building#22]
![IMG_20220731_152710](https://user-images.githubusercontent.com/72664192/182021964-48a6e67d-d401-48e6-8fbc-1994e5a2feb7.jpg)

**Comment by SamirPS** [comment]
He don't find the kernel can you do a ls in this directory ?

**Comment by Saikatsaha1996** [comment]
> He don't find the kernel can you do a ls in this directory ?

I should clone kernel sources? Or it automatically clone when i run comments for build?

**Comment by SamirPS** [comment]
I don't know that @SebaUbuntu

**Comment by SamirPS** [comment]
From the readme @Saikatsaha1996 :

Add a config for your kernel in device/vendor/codename.py (check the example config in device/examples/example.py)
Add kernel sources in kernel/ (in the path that you specified in the config)

**Comment by SebaUbuntu** [comment]
Clearly you didn't clone kernel sources in kernel/asus/msm8937

**Comment by Saikatsaha1996** [comment]
@SebaUbuntu how can I edit my kernel config ?..
only option available for build && clean 
Any options for `menuconfig` ?

`Vmlinux version genaration failed`

![IMG_20220816_170012](https://user-images.githubusercontent.com/72664192/184869415-91cfc07e-2e39-43cc-acf9-c4c3d200320a.jpg)

**Comment by SebaUbuntu** [comment]
> Vmlinux version genaration failed

Not an error, you can ignore it

> how can I edit my kernel config

Edit the defconfig manually

**Comment by Saikatsaha1996** [comment]
> > Vmlinux version genaration failed
> 
> Not an error, you can ignore it
> 
> > how can I edit my kernel config
> 
> Edit the defconfig manually

Okay
